### PR TITLE
restarting this PR from

### PR DESCRIPTION
**Pull request by ohayon**

### CODE REVIEW

**Comment by ohwutup** [comment]
https://github.com/fastlane/fastlane_core/pull/54#discussion_r47980613

**Comment by KrauseFx** [comment]
Ready for review?

**Comment by KrauseFx** [comment]
Ready for review?

**Comment by ohwutup** [comment]
yep!

**Comment by KrauseFx** [comment]
Code looks good, could you add a one line comment for each of this methods and their return types (e.g. String`

**Comment by KrauseFx** [comment]
In particular it's not clear what `default_build_settings` returns

**Pull request merged**
