### PR TITLE
There is no need for shellwords when the commands are between single quotes

### PR DESCRIPTION
**Pull request by jedi4ever**
Image a password that contains single, double, star, exclamation marks etc... 
With the the shellwords the password gets escaped without any need. As long as the password is between single quotes , we're good.
The only thing we need to do , is escape the single quotes.

### CODE REVIEW

**Comment by KrauseFx** [comment]
Hey @jedi4ever, sorry I didn't come back to this earlier. 

Does that mean I can either quote the value and escape the `'` or use `Shellwords`, but without quotation of the value?

**Comment by jedi4ever** [comment]
afaik yes, but it has to be single quotes, not double quotes they have special meaning in the shell

**Comment by hhanesand** [comment]
Could this have anything to do with the trouble fastlane was having with passwords that contained symbols?

**Comment by mpirri** [comment]
Thanks so much for this pull request!

Sorry for the delay in reviewing this in more detail. Inspired by your comment about symbols in passwords I experimented a bit with this. As you know, this code is used to build and execute a command line of this form:

`"/Applications/Xcode.app/Contents/Developer/../Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter" -m upload -u "<apple_id>" -p '<password>' -f '/tmp/1082782634.itmsp'  -t 'Signiant' -k 100000`

It turns out that iTMSTransporter expects a shell-escaped password to be passed in the -p parameter. So, we need this ShellEscape to properly 

To prove this to myself, I messed around with my appleId password a bit. I changed it to:
`Password"?!*1234`
(all the characters except single-quote)

In this case, ShellEscaping still worked. Using the code you suggest, I got this error from iTMSTransporter:
`/Applications/Xcode.app/Contents/Developer/../Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter: eval: line 255: unexpected EOF while looking for matching ``"'
/Applications/Xcode.app/Contents/Developer/../Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter: eval: line 256: syntax error: unexpected end of file`
In short, the un-escaped single-quote confused it.

So, it seems to me that ShellEscaping the password for shell-use is the right approach.

Okay, so, what about single-quotes? Well, in this case, neither of the solutions worked! It looks like ShellEscape fails with single-quotes, because the shell won't properly handle the \' within the single quoted password.

For example, use this password:
`Password'1234`
(single quote at the end)

For the ShellEscape technique, this gives the command line:
`"/Applications/Xcode.app/Contents/Developer/../Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter" -m upload -u "<apple_id>" -p 'Password\'1234' -f '/tmp/1082782634.itmsp'  -t 'Signiant' -k 100000`
This confuses the shell as it wants to use the single-quote in the password to trigger multi-line mode.

Turns out, we actually need to escape single quotes using like this:
`"/Applications/Xcode.app/Contents/Developer/../Applications/Application Loader.app/Contents/itms/bin/iTMSTransporter" -m upload -u "<apple_id>" -p 'Password'"\'"'1234' -f '/tmp/1082782634.itmsp'  -t 'Signiant' -k 100000`

In short, when we encounter a single-quote, replace it with a single quote (to end the previous string), a double-quote/backslash/single-quote/double-quote string to represent the escaped backslash/single-quote, and then another single quote to encapsulate the rest of the string.

So, I think the correct change is to replace the ShellEscape line with this code instead:
`Shellwords.escape(password).gsub("\\'") do`
`    "'\"\\'\"'"`
`end`

I will open a pull request for this shortly and attach a link here, so you can experiment with some of your own passwords and let us know if this works for you.

Thanks again!

**Comment by mpirri** [comment]
This is the PR that has my updated code:
https://github.com/fastlane/fastlane_core/pull/100

I'm closing this PR, please feel free to open another PR if you have an example of a password that is not handled properly by the code in this above PR.

Thanks again for contribution and for helping us think this through!

**Pull request closed without merging**
