### PR TITLE
Added CI detection when run from TeamCity, Go and Bamboo

### PR DESCRIPTION
**Pull request by xfreebird**

### CODE REVIEW

**Comment by KrauseFx** [comment]
Are you sure that's the way to go? Don't they set a standard environment variable as well, like `CI`?

**Comment by xfreebird** [comment]
Yes, I checked for Bamboo, it doesn't set ```CI``` env variable. The rest I grabbed from official documentation of default environment variables.

**Comment by xfreebird** [comment]
I checked for TeamCity and GoCD, there is no ```CI``` env variable.

**Comment by KrauseFx** [comment]
Interesting, thanks @xfreebird :+1:

**Pull request merged**
