### PR TITLE
[WIP] Fixes fastlane/match#72 (PTY reading behavior is system dependent in ruby)

### PR DESCRIPTION
**Pull request by lacostej**
This patch now solve 2 problems
- makes PTY more resilient (solves fastlane/match#72
- make pty optional and allow an open3 based backend.  Note that the open3 backend might be affected by the ran program to buffer or not its output in non terminal environments.

Some notes:
- the change is meant to be backward compatible: by default pty is still the default runner. open3 backend can be forced using environment variable or selected if not present on platform 
- I’ve split it into 4 commits so that each individual changes can be looked into
- I’ve added some unit tests
- I can split it into 2 PRs if we want to solve the 2 issues separately

What's missing:
- gemspec changes to add open3 library and make pty optional
- documentation

As for the "make PTY more resilient" change, while I believe that some causes of the exception happening might be removed if we properly synced both stdout and stderr (I don't think both are synced properly today), nevertheless catching the raised exceptions that occur when the underlying process has exited sounds like normal practice when using PTY.spawn().

### CODE REVIEW

**Comment by KrauseFx** [comment]
Could you describe on why this change is necessary and what changes?

**Comment by lacostej** [comment]
I've worked a bit more on this (changed not pushed) so I consider this a WIP still. I was trying to add more features, like provide an alternative to PTY but I don't find an easy way to get rid of the lost buffering. Not even sure if possible...

Keeping this open for discussion.

**Comment by lacostej** [comment]
Here's a work in progress that solves both this and the ability to switch to a non PTY based implementation. https://github.com/lacostej/fastlane_core/tree/safe_pty_and_popen

Is this the direction we want to go ? I.e. plugin based Runner that depends on the available dependencies ? The code can obviously be cleaned up.

I am testing it that way:

```
FASTLANE_NO_TTY=something  fastlane ...
```

It tries by default to use tty and fallback to open3 except if you force tty out.

**Comment by lacostej** [comment]
Please give me feedback on whether we want to go that way, and I ll squash the commits / rebase as needed. Thanks !

**Comment by asfalcone** [comment]
@lacostej Thanks for the effort on this PR. We've decided not to introduce this behavior right now since it  has the potential to impact all of the tools and requires a lot of testing, especially on different platforms (like mac, linux and windows). There is definitely some good code in here that we may want to include in the future though, with more time to test! :lollipop:

**Comment by lacostej** [comment]
@asfalcone BTW, if necessary, I can re-add the same feature, after switching to monorepo, in a different patch order, to better show reviewers that the default behaviour is unchanged code wise, except for the catching of some child process issues

I voluntarily made the [changes in separate commits](https://github.com/fastlane/fastlane_core/pull/73/commits) to be able to follow the changes easily
1. catch child process issues https://github.com/lacostej/fastlane_core/commit/1b123c536e880a0648ca169fbae6526c2a1c8c82
2. refactor code to reuse a single rescue https://github.com/lacostej/fastlane_core/commit/55a6836fad421b0b892f21c0cd7c9d2d2c8764af
3. move code into a separate module https://github.com/lacostej/fastlane_core/commit/4c13ef86600468658a3ac55b30949863cdfaf227
4. provide alternate implementation https://github.com/lacostej/fastlane_core/commit/36a2270a85122d24dbac2c46caf87795dd48834b

For example, patch #1 could be skipped if we focus on wanting to provide a non pty based runner.

**Comment by asfalcone** [comment]
@lacostej that would be great! It would also be awesome if you could recruit some help in testing the changes on various OSes. That would help us feel more confident in the changes :+1:

**Pull request closed without merging**
