### PR TITLE
Use backticks in projects

### PR DESCRIPTION
**Pull request by KrauseFx**
To have a nicer output

### CODE REVIEW

**Comment by mfurtak** [comment]
If `print` is `false`, will you get any of the nicer output?

**Comment by KrauseFx** [comment]
Then it's more output. The reason I added this was to have less output since the setup already prints out a lot of stuff, and this line is not really important to the user

**Comment by mfurtak** [comment]
Ah, I see. nicer in this case means less - cool! :rocket: :ship: it!

**Comment by KrauseFx** [comment]
Sorry, I should have been more clear with the PR body :+1:

**Pull request merged**
