### PR TITLE
Removed class variables

### PR DESCRIPTION
**Pull request by KrauseFx**

### CODE REVIEW

**Comment by i2amsam** [comment]
These appear to be legit test failures ^

**Comment by KrauseFx** [comment]
Nope, tests are passing locally.

**Comment by i2amsam** [comment]
I think it just needs to be rebased @KrauseFx, looks like it was branched off a failing base.

**Comment by KrauseFx** [comment]
Moved to https://github.com/fastlane/fastlane_core/pull/110

**Pull request closed without merging**
